openapi: 3.0.0
info:
  title: Magic Transporters API
  version: 1.0.0
  description: API documentation for Magic Transporters
paths:
  /api/magic-items:
    post:
      summary: Add a new Magic Item
      tags:
        - MagicItems
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MagicItem'
      responses:
        201:
          description: The created Magic Item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MagicItem'
        500:
          description: Server error
components:
  schemas:
    MagicItem:
      type: object
      required:
        - name
        - weight
      properties:
        name:
          type: string
          description: The name of the magic item
        weight:
          type: number
          description: The weight of the magic item
      example:
        name: Magic Wand
        weight: 10
